---
- hosts: all
  become: yes
  vars:
    docker_compose_version: 1.26.0
  handlers:
  - name: docker status
    systemd:
      state: started
      name: docker
  - name: docker restart
    systemd:
      state: restarted
      daemon_reload: true
      name: docker
  tasks:
  - name: install packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - dirmngr
      - gnupg2

  - name: add apt keys
    apt_key:
      url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
      state: present

  - name: add debian repos
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
      state: present
      filename: docker

  - name: install docker
    notify:
    - docker status
    apt:
      name: docker-ce
      state: latest
      update_cache: yes

  - name: make systemd docker fragment dir
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory

  - name: make docker dir
    file:
      path: /etc/docker
      state: directory

  - name: make docker config
    notify:
    - docker restart
    copy:
      src: etc/docker/daemon.json
      dest: /etc/docker/daemon.json

  - name: install docker compose
    get_url:
      url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
      dest: /usr/local/bin/docker-compose
      mode: 0544
      owner: root
      group: root
