---
- hosts: all
  tasks:
  - name: add packages
    become: yes
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - git
      - zsh

  - name: get oh-my-zsh install.sh
    get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: "{{ ansible_env.HOME }}/install.sh"
      mode: 0755

  - name: install oh-my-zsh
    command:
      cmd: sh "{{ ansible_env.HOME }}/install.sh" --unattended
      creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
      #
      #  - name: change login shell to zsh
      #    become: yes
      #    user:
      #      name: "{{ ansible_env.USER }}"
      #      shell: /bin/zsh
      #      state: present
      #
  - name: get ZSH_CUSTOM
    set_fact:
      zsh_custom: "{{ lookup('env', 'ZSH_CUSTOM') }}"

  - name: get zsh_custom default
    set_fact:
      zsh_custom: "{{ ansible_env.HOME }}/.oh-my-zsh/custom"
    when: zsh_custom|length == 0

  - name: clone zsh plugin git repos
    git:
      repo: "{{ item }}"
      dest: "{{ zsh_custom }}/plugins/{{ item | basename | regex_replace('.git', '') }}"
    loop:
    - https://github.com/zsh-users/zsh-autosuggestions.git
    - https://github.com/zsh-users/zsh-syntax-highlighting.git

  - name: clone powerlevel10k plugin git repo
    git:
      repo: https://gitee.com/romkatv/powerlevel10k.git
      depth: 1
      dest: "{{ zsh_custom }}/themes/powerlevel10k"

  - name: copy zsh config
    copy:
      src: home/{{ item }}
      dest: "{{ ansible_env.HOME }}"
      owner: "{{ ansible_env.USER }}"
      group: "{{ ansible_env.USER }}"
      mode: 0600
    loop:
    - .zshrc
    - .p10k.zsh
