---
- hosts: all
  vars:
  - packer_version: 1.6.0
  tasks:
  - name: install packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - dirmngr
      - gnupg2
      - unzip

  - name: get hashicorp gnupg key
    command: gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 91A6E7F85D05C65630BEF18951852D87348FFC4C

  - name: get hashicorp sha256 sums
    get_url:
      url: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_SHA256SUMS
      dest: /tmp/packer_{{ packer_version }}_SHA256SUMS

  - name: get hashicorp sigs
    get_url:
      url: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_SHA256SUMS.sig
      dest: /tmp/packer_{{ packer_version }}_SHA256SUMS.sig

  - name: verify hashicorp sigs
    command:
      cmd: gpg --verify /tmp/packer_{{ packer_version }}_SHA256SUMS.sig

  - name: get packer
    get_url:
      url: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_{{ ansible_system | lower }}_{{ (ansible_architecture == 'x86_64') | ternary('amd64', ansible_architecture) }}.zip
      dest: /tmp/packer_{{ packer_version }}_{{ (ansible_architecture == 'x86_64') | ternary('amd64', ansible_architecture) }}.zip
      checksum: sha256:https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_SHA256SUMS

  - name: create packer group
    become: yes
    group:
      name: packer
      system: yes
      state: present

  - name: install packer
    become: yes
    unarchive:
      src: /tmp/packer_{{ packer_version }}_{{ (ansible_architecture == 'x86_64') | ternary('amd64', ansible_architecture) }}.zip
      mode: 0550
      owner: root
      group: packer
      dest: /usr/local/bin
