---
- hosts: all
  tasks:
  - name: install packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - dirmngr
      - gnupg2

  - name: add vscode key
    become: yes
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: add vscode repo
    become: yes
    apt_repository:
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
      state: present
      filename: vscode

  - name: install vscode
    become: yes
    apt:
      name: code
      update_cache: yes
      state: latest
